#!/bin/bash

### DOCUMENTATION ####################

: <<DESCRIPTION
	Install my command-line tools on the local machine.
DESCRIPTION

: <<USAGE

USAGE

######################################

# detect the operating system
platform='unknown'
unamestr=`uname`
if [[ "$unamestr" == 'Linux' ]]; then
	platform='linux'
elif [[ "$unamestr" == 'Darwin' ]]; then
	platform='mac'
else
	echo $'\e[31mSorry, your operating system is not supported.\e[39m'
	exit
fi


# scripts directory
SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
	SCRIPTDIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
	SOURCE="$(readlink "$SOURCE")"
	[[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
SCRIPTDIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"

SCRIPTSDIR="$SCRIPTDIR/scripts"
BINDIR="$SCRIPTDIR/bin"

rm -rf "$BINDIR" # clean BINDIR
mkdir -p "$BINDIR" # create BINDIR silently

# execute all install scripts inside SCRIPTSDIR
INSTALLSCRIPTS=`find $SCRIPTSDIR -name 'install'`
for install in $INSTALLSCRIPTS
do
	$install
done


scripts=`grep -Rl '^#!/' $SCRIPTSDIR` # find all executable files (heuristically) in "scripts" dir
for script in $scripts # for each such file
do
	filename=`basename $script`
	chmod gu+x $script # make it executable
	if [[ ! $filename == 'install' ]] && [[ ! $filename == _* ]] ; then
		ln -sf "$script" "$BINDIR" # create a symbolic link to it in BINDIR
	fi
	# if [[ $filename == 'install' ]] ; then # remember install scripts to execute later
	# 	INSTALLSCRIPTS+=("$script")
	# fi
done


# permanently add the BINDIR and SCRIPTDIR directories to PATH
if [[ $platform == 'linux' ]]; then
	touch -am ~/.bash_profile ~/.bashrc
	# remove old records from .bash_profile and .bashrc
	sed -i.bak '/#my-tools/d' ~/.bash_profile && rm ~/.bash_profile.bak
	sed -i.bak '/#my-tools/d' ~/.bashrc && rm ~/.bashrc.bak

	echo 'export PATH=$PATH:'"$SCRIPTDIR:$BINDIR"' #my-tools' >> ~/.bash_profile
	echo 'export PATH=$PATH:'"$SCRIPTDIR:$BINDIR"' #my-tools' >> ~/.bashrc
elif [[ $platform == 'mac' ]]; then
	echo "Adding to PATH..."
	sudo -s "echo '"$SCRIPTDIR:$BINDIR"' > /etc/paths.d/mytools"
fi

# Installing packages
# for install in "${INSTALLSCRIPTS[@]}"
# do
# 	$install
# done


# now make all scripts executable
echo "Restart the terminal for PATH update."


# OLD: find all script-containing directories
# function join { local IFS="$1"; shift; echo "$*"; }
# DIRS=`grep -Rl '^#!.*bash' $SCRIPTSDIR | sed 's/\(.*\/\)\(.*\)/\1/' | sort | uniq`
# DIRS_STR=`join ':' $DIRS`	