#!/usr/bin/env bash

### DOCUMENTATION ####################

: <<DESCRIPTION
	Update MyTools
DESCRIPTION

: <<USAGE

USAGE

: <<ADDITIONAL

ADDITIONAL

######################################

# script directory
SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  SCRIPTDIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
SCRIPTDIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"


cd "$SCRIPTDIR"
git fetch origin master
git reset --hard origin/master