#!/usr/bin/env bash

echo -n "Installing Virtuoso management tools"

echo -n "Type your Virtuoso password for dba (default is 'dba'): "
read isqlpass
[[ -z  $isqlpass  ]] && isqlpass="dba" # default value if empty

host="127.0.0.1"
isqlPort="1111"
sparqlPort="8890"

confJson="{
	\"virtuoso-host\": 				\"$host\",
	\"virtuoso-isql-port\": 		\"$isqlPort\",
	\"virtuoso-sparql-port\": 		\"$sparqlPort\",
	\"virtuoso-dba-password\": 		\"$isqlpass\"
}"

# script directory
SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  SCRIPTDIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
SCRIPTDIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"

cd "$SCRIPTDIR"
echo "$confJson" > "config.json"
../project-compile/project-compile
rm "config.json"