#!/usr/bin/env bash


# script directory
SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  SCRIPTDIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
SCRIPTDIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"

cd "$SCRIPTDIR"

if [ ! -f "$SCRIPTDIR/config.json" ]; then
	echo "Installing Virtuoso management tools"

	echo -n "Type your Virtuoso password for dba (default is 'dba'): "
	read -s isqlpass
	[[ -z  $isqlpass  ]] && isqlpass="dba" # default value if empty

	echo

	host="127.0.0.1"
	isqlPort="1111"
	sparqlPort="8890"

	confJson="{
		\"virtuoso-host\": 				\"$host\",
		\"virtuoso-isql-port\": 		\"$isqlPort\",
		\"virtuoso-sparql-port\": 		\"$sparqlPort\",
		\"virtuoso-dba-password\": 		\"$isqlpass\"
	}"

	echo "$confJson" > "config.json"
fi

../project-compile/project-compile
