#!/usr/bin/env bash

### DOCUMENTATION ####################

: <<DESCRIPTION
	Execute SQL or SPARQL in isql terminal
DESCRIPTION

: <<USAGE
	./virtuoso-isql-exec somescript.sql
USAGE

######################################

/usr/local/virtuoso-opensource/bin/isqlw 127.0.0.1:1111 dba 'dba' "$1"
