#!/usr/bin/env bash

### DOCUMENTATION ####################

: <<DESCRIPTION
	Show all opened ports
DESCRIPTION

: <<USAGE
USAGE

######################################

printf "%-10s%-20s%-20s\n" 'Port' 'Prog' 'User'
echo '--------------------------------------------------'
sudo lsof -i -P | grep -i "listen" | awk '{printf "%s\t%s\t%s\n", $9, $1, $3}' | rev | cut -s -f1 -d: | rev | sort | uniq | awk '{printf "%-10s%-20s%-20s\n", $1, $2, $3}'