#!/usr/bin/env bash

### DOCUMENTATION ####################

: <<DESCRIPTION
	Show all opened ports
DESCRIPTION

: <<USAGE
USAGE

######################################

printf "%s\t%s\t\t%s\n" 'Port' 'Prog' 'User'
echo '---------------------'
sudo lsof -i -P | grep -i "listen" | awk '{print $9 "\t" $1 "\t\t" $3}' | rev | cut -s -f1 -d: | rev | sort | uniq